### ISSUE TITLE
How does fish-nvm compare to fast-nvm-fish?

### ISSUE THREAD

**Issue by jorgebucaran** [FabioAntunes/fish-nvm#31]
@FabioAntunes 👋 

I'm trying to improve the Awesome Fish list and noticed both this package and @brigand's [fast-nvm-fish](https://github.com/brigand/fast-nvm-fish) are [**nvm**](https://github.com/creationix/nvm) wrappers (require nvm to be previously installed) and I was wondering how does one compare to the other. I plan to include both in the list, but I don't want to repeat myself.

This is what I have. 

- [brigand/**fast-nvm-fish**](https://github.com/brigand/fast-nvm-fish) - Efficient [nvm](https://github.com/creationix/nvm) wrapper
- [FabioAntunes/**fish-nvm**](https://github.com/FabioAntunes/fish-nvm) - Completion-rich [nvm](https://github.com/creationix/nvm) wrapper

But it begs the question: isn't fish-nvm efficient or fast-fish-nvm completion-rich too?

**Comment by FabioAntunes** [comment]
So the main difference is that, https://github.com/brigand/fast-nvm-fish partially uses nvm, it's not actually a nvm wrapper because it manipulates the PATH instead of letting nvm doing it.

As fish-nvm is a wrapper around nvm, it's just a set of alias that allows you to delay the sourcing of nvm until is actually used. 

The main issue with nvm being slow is that, when it's manipulating the path it calls `npm config get prefix` and there's a whole issue related to explaining that https://github.com/creationix/nvm/issues/1596

So if really need to run as closest as possible to the original `nvm` because reasons then `fish-nvm` is the right tool.

If you just want a fast nvm for local development then `fast-nvm-fish` maybe is the best.

Also I think `fish-nvm` has **Completion-rich** description because It actually provides fish completion to the nvm command

**Comment by jorgebucaran** [comment]
@FabioAntunes Thank you!! I'll describe them as follows. Hope it's fine. 

- brigand/**fast-nvm-fish** - Enhanced nvm wrapper optimized for speed
- FabioAntunes/**fish-nvm** - Completion-rich, true nvm wrapper
